### ISSUE TITLE
Policy cost reporting sanity check

### ISSUE THREAD

**Issue by johanneskoch94** [pik-piam/remind#100]
Hi, 
I put this in after discussions with Lavinia and Björn, so that automatic policy cost reporting only happens when the the gdp_scenarios are the same between policy and reference runs. This was done so that policy cost weren't reported for nonsensical policy-reference pairs. 
The output.R script [policyCosts.R](https://github.com/remindmodel/remind/blob/develop/scripts/output/comparison/policyCosts.R) was supposed to be used to create specific policy costs reportings.   
Should this be changed? What should to be done instead? @fbenke-pik @LaviniaBaumstark @bs538 @strefler 

https://github.com/pik-piam/remind/blob/fed4b488a714e2603e39bcc8feb3dd78925fd14a/R/convGDX2MIF.R#L57-L74

**Comment by LaviniaBaumstark** [comment]
I still think that it is good to calculate the policy cost only if the GDP-scenarios were the same. Otherwise it might be interpret in a wrong way and we really should avoid this. In addition, the policy cost can be calculated in reference to many different scenarios (e.g. base, NPi, delay, etc.) which all can be correct and depends on the research question of the analysis. So, I vote for keeping it as it is.

**Comment by strefler** [comment]
The problem is, that cm_GDPscen is not written to the gdx. So policy costs are actually never reported and always have to be added afterwards.

**Comment by LaviniaBaumstark** [comment]
in core/sets.gms the following lines should ensure that this information is in the gdx:
SETS
* Save select compiler flags as sets, to make them accessible from the final gdx
c_expname       "c_expname as set for use in GDX"       /%c_expname%/
cm_GDPscen      "cm_GDPscen as set for use in GDX"      /%cm_GDPscen%/
*
Are you using an old REMIND version? or is this not working?

**Comment by LaviniaBaumstark** [comment]
in my runs for the technical REMIND paper the information on cm_GDPscen is in the gdx - just checked

**Comment by LaviniaBaumstark** [comment]
but no policy costs are reported, there seems to be a bug in the sensible check, @johanneskoch94, please, could you fix this

**Comment by johanneskoch94** [comment]
Yes! Thanks for your input.

**Comment by johanneskoch94** [comment]
OK. So there is no bug in the sensibility check.
The reason @strefler that the policy costs aren't computed automatically for you, is that you're using an old remind version (see Lavinia's comment above), where 
https://github.com/remindmodel/remind/blob/d6b54940165364c3a884bf6933d3d137bd572198/core/sets.gms#L15-L17
doesn't include the line `cm_GDPscen "cm_GDPscen as set for use in GDX" /%cm_GDPscen%/` yet.
