### ISSUE TITLE
Rename Transport UE

### ISSUE THREAD

**Issue by Loisel** [pik-piam/remind#122]
"Useful Energy" in the transport sector is not consistent with the common understanding of this term. Instead, UE in the REMIND transport sector is a *combustion car equivalent*, i.e., from one unit of fepet, `apCarPeT` produces one unit of UE, while `apCarElT` produces around 3 units of UE etc.

I tried to fix it once but it proved more difficult than expected (as almost always). Please contact me if you care to fix this. Maybe also a thing for remind2 @Renato-Rodrigues

**Comment by Renato-Rodrigues** [comment]
I would be in favor of completely moving from the UE paradigm in transport and focus our efforts in reporting variables at the energy services levels and FE use instead.
Remind2 reportFE and comparison scenario plots already exclude UE transport related code and plots to lessen this confusion.

If you agree with that I think we can consider this topic closed.

**Comment by Loisel** [comment]
Agreed.
