### ISSUE TITLE
compareScenarios does not support starting years > 2005

### ISSUE THREAD

**Issue by Loisel** [pik-piam/remind#123]
When using years > 2005 for the `y` parameter in `compareScenarios`, the script fails without a readable traceback.
```
> compareScenarios(
+   def_mifs,
+   "~/git/REMIND/core/input/historical/historical.mif", y=seq(2015, 2055, 5), y_bar = c(2015, 2030, 2050),
+   fileName="compareScenarioDefault_shortTerm.pdf")
Error in if (magclass::getNames(data_new, fulldim = TRUE)[["scenario"]] %in%  (from compareScenarios.R#163) : 
  argument is of length zero
> traceback()
1: compareScenarios(def_mifs, "~/git/REMIND/core/input/historical/historical.mif", 
       y = seq(2015, 2055, 5), y_bar = c(2015, 2030, 2050), fileName = "compareScenarioDefault_shortTerm.pdf")
```

**Comment by giannou** [comment]
where do I find the object `def_mifs`?

**Comment by giannou** [comment]
and which git commit are you at? are we not using `remind2` now?

**Comment by Loisel** [comment]
> and which git commit are you at? are we not using `remind2` now?

My initial tests on remind2 failed so I thought it is maybe still work-in-progress, so I fell back to remind. But will test for remind2 again and provide a reproducible example. Closing.
