### ISSUE TITLE
SE|Gases lower that FE|Gases

### ISSUE THREAD

**Issue by piklev** [pik-piam/remind#13]
This is at least the case in the USA in 2100, for a budget 600 scenario (e.g. /p/projects/remind/runs/sspsdp_validation/remind-standalone/output/SSP2-Budg600_2019-09-16_01.43.03)
Not fully clear whether this is a reporting issue or a model issue.
This may also impact the emissions accounting.

**Comment by piklev** [comment]
This comes from the fact that reused waste gases from landfills are not reported in SE| Gases

From `core/equations.gms`
`( 0.001638 `
`    * ( vm_macBase(t,regi,"ch4wstl")`
`      - vm_emiMacSector(t,regi,"ch4wstl")`
`      )`
`    )$( sameas(enty2,"segabio") AND t.val gt 2005 )`

Should I just add this to SE|Gases or are there any factors that I should consider?

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
It seems as if that [used to be the case](https://github.com/pik-piam/remind/blob/5ec648ab68b8ef1e3174fcc2d8a2c3ad4eaf8635/R/reportSE.R#L279), but got [lost on the way](https://redmine.pik-potsdam.de/projects/mo/repository/revisions/9642/diff/remind/R/reportSE.R) about four years ago.
Best ask @giannou and Jess about it.

**Comment by piklev** [comment]
@Anastasis do you have any idea why the line was commented out? 
I have prepared a "cleaner" version of this line (because I did not know about it) which is ready to be committed. Let me know if the out-commenting was accidental.

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
Pretty sure "@&#8203;Anastasis" is not @giannou. Somebody who didn't know about the glorious `remind` package now probably does :)

**Comment by piklev** [comment]
Edited

**Comment by giannou** [comment]
looks like something that was just temporary, thanks @piklev for letting us know. I'd say you can commit, (run a test before, if you can)

**Comment by piklev** [comment]
what about the line just above? Should it be outcommented?
(In the end I would just uncomment. My version had some issues)

**Comment by giannou** [comment]
i think we should leave the line above alone, or ask @dklein-pik: https://redmine.pik-potsdam.de/projects/mo/repository/diff/remind?utf8=%E2%9C%93&rev=10032&rev_to=10019
