### ISSUE TITLE
Variable "Res|Average Extraction Costs|XXX" is not reported for realisation 31_fossil:grades2poly (the default)

### ISSUE THREAD

**Issue by giannou** [pik-piam/remind#16]

**Comment by giannou** [comment]
function `call calcAvgExtractionCosts("pecoal", fuelex, fuelex_cum[,c(2000,t),], grades)` in file [https://github.com/pik-piam/remind/blob/master/R/reportExtraction.R](url) stops with error:

> Error in .mselect_coords(x, ...) : 
>   Dimnames must have names in order to use mselect!

**Comment by giannou** [comment]
cannot assign Jerome because he's not in pik-piam

**Comment by jhilaire** [comment]
Thanks for the invite, I'm a member now. I won't have time to look into this issue this week. Doesn't this function only work with grades? I'll check that asap most probably next week

**Comment by giannou** [comment]
If this function only works with grades then the question is how do we report extraction costs in grades2poly? Any help would be greatly appreciated, and of course it can wait until you have some time

**Comment by jhilaire** [comment]
Another question is: is that a new bug or has it been here since 2016? It seems weird that this has not been detected earlier...

**Comment by giannou** [comment]
I checked, it's not new. Runs of 2016 and 2017 report zero extraction costs as well

**Comment by jhilaire** [comment]
Do you have a gdx I could use for testing purposes?

**Comment by giannou** [comment]
here's one: /home/giannou/REMIND/output/default_2020-02-28_10.10.40/fulldata.gdx

Thanks a million!

**Comment by jhilaire** [comment]
Should work now.
