### ISSUE TITLE
over-reporting of FEs that have non-zero offset_quantity

### ISSUE THREAD

**Issue by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [pik-piam/remind#36]
Silvia discovered a discrepancy in the .mif files between `FE|Buildings|Hydrogen` + `FE|CDR|Hydrogen` + `FE|Industry|Hydrogen` + `FE|Transport|Hydrogen` and `FE|Hydrogen`.  Turns out this is exactly 0.000315 EJ/yr or 1e-5 TWa.

```
# A tibble: 13 x 11
   scenario       period region Buildings     CDR Industry Transport    Total reported      diff
   <fct>           <int> <fct>      <dbl>   <dbl>    <dbl>     <dbl>    <dbl>    <dbl>     <dbl>
 1 SSP2-PkBudg900   2005 CAZ     0.000315 0        0.0112   0         0.0115   0.0112  -0.000315
 2 SSP2-PkBudg900   2005 CHA     0.000315 0        0.0551   0         0.0554   0.0551  -0.000315
 3 SSP2-PkBudg900   2005 EUR     0.000315 0        0.0561   0         0.0564   0.0561  -0.000315
 4 SSP2-PkBudg900   2005 IND     0.000315 0        0.0154   0         0.0157   0.0154  -0.000315
 5 SSP2-PkBudg900   2005 JPN     0.000315 0        0.0152   0         0.0155   0.0152  -0.000315
 6 SSP2-PkBudg900   2005 LAM     0.000315 0        0.0220   0         0.0223   0.0220  -0.000315
 7 SSP2-PkBudg900   2005 MEA     0.000315 0        0.0213   0         0.0216   0.0213  -0.000315
 8 SSP2-PkBudg900   2005 NEU     0.000315 0        0.00920  0         0.00951  0.00920 -0.000315
 9 SSP2-PkBudg900   2005 OAS     0.000315 0        0.0262   0         0.0265   0.0262  -0.000315
10 SSP2-PkBudg900   2005 REF     0.000315 0        0.0200   0         0.0203   0.0200  -0.000315
11 SSP2-PkBudg900   2005 SSA     0.000315 0        0.0131   0         0.0134   0.0131  -0.000315
12 SSP2-PkBudg900   2005 USA     0.000315 0        0.0678   0         0.0681   0.0678  -0.000315
13 SSP2-PkBudg900   2005 World   0.00378  0        0.333    0         0.336    0.333   -0.00378
```

Shouldn't https://github.com/pik-piam/remind/blob/b4934efe1a1b439f03b8c677c0fb0fd4e3d21f81/R/reportFE.R#L147-L153 account for `pm_cesdata(t,regi,ppfen,"offset_quantity")`?  Probably https://github.com/pik-piam/remind/blob/b4934efe1a1b439f03b8c677c0fb0fd4e3d21f81/R/reportFE.R#L279-L284 and https://github.com/pik-piam/remind/blob/b4934efe1a1b439f03b8c677c0fb0fd4e3d21f81/R/reportFE.R#L482-L497 too.  Same for the other realisations of modules 36, 37, and 38.

**Comment by piklev** [comment]
@Silvia: could you please send me the link to the gdx?
    
    On 22/04/2020 09:42, Michaja Pehl
      wrote:
    
    
      
      Silvia discovered a discrepancy in the .mif files between FE|Buildings|Hydrogen
        + FE|CDR|Hydrogen + FE|Industry|Hydrogen
        + FE|Transport|Hydrogen and FE|Hydrogen.
        Turns out this is exactly 0.000315 EJ/yr or 1e-5 TWa.
      # A tibble: 13 x 11
   scenario       period region Buildings     CDR Industry Transport    Total reported      diff
   <fct>           <int> <fct>      <dbl>   <dbl>    <dbl>     <dbl>    <dbl>    <dbl>     <dbl>
 1 SSP2-PkBudg900   2005 CAZ     0.000315 0        0.0112   0         0.0115   0.0112  -0.000315
 2 SSP2-PkBudg900   2005 CHA     0.000315 0        0.0551   0         0.0554   0.0551  -0.000315
 3 SSP2-PkBudg900   2005 EUR     0.000315 0        0.0561   0         0.0564   0.0561  -0.000315
 4 SSP2-PkBudg900   2005 IND     0.000315 0        0.0154   0         0.0157   0.0154  -0.000315
 5 SSP2-PkBudg900   2005 JPN     0.000315 0        0.0152   0         0.0155   0.0152  -0.000315
 6 SSP2-PkBudg900   2005 LAM     0.000315 0        0.0220   0         0.0223   0.0220  -0.000315
 7 SSP2-PkBudg900   2005 MEA     0.000315 0        0.0213   0         0.0216   0.0213  -0.000315
 8 SSP2-PkBudg900   2005 NEU     0.000315 0        0.00920  0         0.00951  0.00920 -0.000315
 9 SSP2-PkBudg900   2005 OAS     0.000315 0        0.0262   0         0.0265   0.0262  -0.000315
10 SSP2-PkBudg900   2005 REF     0.000315 0        0.0200   0         0.0203   0.0200  -0.000315
11 SSP2-PkBudg900   2005 SSA     0.000315 0        0.0131   0         0.0134   0.0131  -0.000315
12 SSP2-PkBudg900   2005 USA     0.000315 0        0.0678   0         0.0681   0.0678  -0.000315
13 SSP2-PkBudg900   2005 World   0.00378  0        0.333    0         0.336    0.333   -0.00378

      Shouldn't https://github.com/pik-piam/remind/blob/b4934efe1a1b439f03b8c677c0fb0fd4e3d21f81/R/reportFE.R#L147-L153
        account for pm_cesdata(t,regi,ppfen,"offset_quantity")?
        Probably https://github.com/pik-piam/remind/blob/b4934efe1a1b439f03b8c677c0fb0fd4e3d21f81/R/reportFE.R#L279-L284
        and https://github.com/pik-piam/remind/blob/b4934efe1a1b439f03b8c677c0fb0fd4e3d21f81/R/reportFE.R#L482-L497
        too. Same for the other realisations of modules 36, 37, and 38.
      —
        You are receiving this because you were assigned.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/pik-piam/remind/issues/36",
"url": "https://github.com/pik-piam/remind/issues/36",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
