### ISSUE TITLE
FE level reporting is not accurately describing REMIND behavior

### ISSUE THREAD

**Issue by Loisel** [pik-piam/remind#43]
By leaving the paradigm of SE level pooling by state of matter (solid, liquid, gas) with the updates by Renato (fossil and bio distinction on SE level), a lot of FE level reporting does anymore correctly reflect what REMIND is doing.

The reason for this is, that FE distinction by PE carrier (e.g, FE|Transport|Liquids|Biomass) is based on SE level pools that do not exist anymore. An example from the reporting (`reportCrossVariables.R`):

```
tmp <- mbind(tmp,setNames(
                   output[r,,"FE|Transport|Liquids (EJ/yr)"] 
                 * output[r,,"SE|Liquids|Biomass (EJ/yr)"]
                 / output[r,,"SE|Liquids (EJ/yr)"],  "FE|Transport|Liquids|Biomass (EJ/yr)"))

```
If REMIND decides to supply all bioliquids to FE buildings or industry, which it can do now (since the link seliqbio to fehoi is explicit), this will not correctly be reflected in the reporting anymore.

The same issue shows up for all various combinations of carriers and sectors. Possible problems that come to my mind:
- bounds on shares that are defined on the FE level are not in line with the reporting variables (that's how I ran into this issue).
- FE price signals are more difficult to interpret from the reporting.
- Actual tech investments and capacities are not in line with produced amounts.l

One of the reasons why this might be difficult to fix is backward compatibility. In the end, if backward compatibility is to be kept, FE reporting by PE carrier has to be split into the old (`seliq, sega, seso`) variables and a new one which correctly calculates shares on the basis of the new pools, i.e., `seliqfos, seliqbio, sesofos, sesobio, segafos, segabio`.

**Comment by Renato-Rodrigues** [comment]
At the time of the SE split, the necessary changes were made both in the reporting and the gams code to reproduce exactly the same mif reporting file before and after the changes. The commit was made only after that was confirmed.
It came to my attention only recently that part of the SE split changes to the gams model were reverted. I guess the reporting was never reverted back to follow the same decision, creating an incompatibility between the reporting and the model variables.

Looking forward, it was previously discussed with Lavinia and other people involved in REMIND-EU that there will be the need for writing an alternative reporting library anyway in the near future to support necessary emissions accounting improvements. This is already partially implemented in REMIND-EU.
This reporting library can be applied for REMIND version from a specific release forward. 

This can be a great opportunity to streamline and update the REMIND reporting as long as enough people join the effort.

**Comment by Loisel** [comment]
Most of these issues is fixed by now, closing.
